name: jadwalin-discord-bot-compute-engine-deploy

on:
  push:
    branches: 
      - main

env:
  SSH_USER: timothyefraim35

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SSH to GCE VM & perform Discord Bot deployment
      uses: fifsky/ssh-action@master
      with:
        command: |
          echo -e 'DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}\nCOMMAND_PREFIX=?' > jadwalin-discord-bot/.env
          ./deploy-dcbot.sh
        host: ${{ secrets.SSH_HOST_DC_BOT }}
        user: $SSH_USER
        key: ${{ secrets.SSH_PRIVATE_KEY }}